---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: devops-test-app
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/<USER>/devops-test-app
  ref:
    branch: main
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-app
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/node-app
      sourceRef:
        kind: GitRepository
        name: devops-test-app
        namespace: flux-system
  values:
    replicaCount: 2
